#!/usr/bin/env node
/**
 * Regenerate THIRD_PARTY_NOTICES.md. The dependency table is read from
 * package.json and node_modules, so licenses are never typed by hand.
 *
 *   node scripts/notices.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));

function row(name) {
  const file = path.join(ROOT, "node_modules", name, "package.json");
  if (!fs.existsSync(file)) return `| \`${name}\` | not installed | |`;
  const j = JSON.parse(fs.readFileSync(file, "utf8"));
  const lic = typeof j.license === "string" ? j.license : (j.licenses ?? []).map((l) => l.type).join(" OR ") || "see package";
  return `| \`${name}\` | ${lic} | ${j.version} |`;
}

const table = (deps) =>
  ["| Package | License | Version |", "| --- | --- | --- |", ...Object.keys(deps).sort().map(row)].join("\n");

const out = `# Third-party notices

VibeUI is MIT licensed (see [LICENSE](LICENSE)). It builds on the open-source work listed below.
This file is generated by \`node scripts/notices.mjs\`; do not edit the tables by hand.

## What you receive when you copy a component

Only the component files themselves plus four peer dependencies, each installed by you from npm
under its own license:

${table({ clsx: 1, "tailwind-merge": 1, "class-variance-authority": 1, "@phosphor-icons/react": 1 })}

## This repository's dependencies

### Runtime (the showcase site and tooling)

${table(pkg.dependencies)}

### Development

${table(pkg.devDependencies)}

Transitive dependencies are covered by their own package licenses; run \`npm ls --all\` or a tool
such as \`license-checker\` for a full audit.

## Fonts

The showcase site loads these through \`next/font/google\`. They are not bundled in the component
files. All are licensed under the SIL Open Font License 1.1.

| Font | Designer / foundry | License |
| --- | --- | --- |
| Geist, Geist Mono | Vercel and Basement Studio | SIL OFL 1.1 |
| Instrument Serif | Rodrigo Fuenzalida and Jordan Egstad | SIL OFL 1.1 |

## Icons

[Phosphor Icons](https://phosphoricons.com), MIT, via \`@phosphor-icons/react\`.

## Inspiration and acknowledgements

No source code from the projects below was copied into VibeUI. They informed the *ideas*,
vocabulary or conventions, and deserve credit:

- **[shadcn/ui](https://ui.shadcn.com)** (MIT): the copy-owned distribution model, the \`cva\` + \`cn()\`
  pattern, and compound-component naming conventions such as \`Card\`/\`CardHeader\` and
  \`Tabs\`/\`TabsList\`.
- **[ObsidianUI](https://www.obsidianui.dev)** (MIT): the idea of a catalogue of expressive, animated
  "craft" components (dock, trading card, magnetic and hover effects).
- **[Magic UI](https://magicui.design)** (MIT): selective, tasteful motion components such as marquees
  and text reveals.
- **[Origin UI / coss ui](https://coss.com/ui)**: a dense catalogue of app primitives.
- **macOS Dock**: the magnification behavior of \`Dock\` is a common interaction pattern.

As a sanity check, same-named components in shadcn/ui, ObsidianUI and Magic UI were compared with
VibeUI's using an 8-token overlap measure; the overlap was limited to short, idiomatic Tailwind and
\`cva\` boilerplate. That is a mechanical comparison, not a legal opinion.

## Trademarks

"shadcn/ui", "Radix", "Tailwind CSS", "React", "Next.js" and other names belong to their owners.
VibeUI is not affiliated with or endorsed by any of them. Other projects also use the name
"VibeUI"; this one is unrelated to them.
`;

fs.writeFileSync(path.join(ROOT, "THIRD_PARTY_NOTICES.md"), out);
console.log("Wrote THIRD_PARTY_NOTICES.md");
